language: r
sudo: false
cache: packages
git:
  depth: false
apt_packages:
  - libpoppler-cpp-dev
  - libudunits2-dev
  - libgdal-dev
  - libgeos-dev
  - libproj-dev
notifications:
  email:
    recipients:
    - mbafs2012@gmail.com
    on_success: change
    on_failure: change
after_success:
    - Rscript -e 'covr::codecov()'