language: r
sudo: false
cache: packages
git:
  depth: false
notifications:
  email:
    recipients:
    - mbafs2012@gmail.com
    on_success: change
    on_failure: change
after_success:
    - Rscript -e 'covr::codecov()'