on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 12 * * *"
    
name: build 

jobs:
  render:
    name: build
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: |
          install.packages(c("dplyr", "rmarkdown", "knitr", "tidyr", "extrafont", "remotes", "flextable"))
          remotes::install_github("tbep-tech/tbeptools")
        shell: Rscript {0}
      - name: Build water atlas content
        run: Rscript -e 'source("wateratlas_source.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Re-build data and create content' || echo "No changes to commit"
          git push origin || echo "No changes to commit"